estk/log4rs

src/toml/mod.rs
`connect()` is missing in both stable and nightly
=> Fix build: `connect` method is missing

src/append/console.rs, src/append/file.rs, src/append/mod.rs, src/encode/mod.rs, src/encode/pattern/mod.rs, src/filter/mod.rs, src/filter/threshold.rs, src/lib.rs
The previous locking strategy required taking a mutex regardless of whether the record is accepted by the filter. This leads to a lot of synchronization in multithreaded programs making extensive use of log
macros. Since a common code path is calling log, applying a filter, and throwing the record away, it makes sense to be able to do this in parallel. To accomplish this, the `inner` Mutex was changed to a RwLock. Since `&mut self` methods can't be called with a read lock, the Append, Filter, and Encode traits need to implement Sync, and their implementors must use interior mutability where needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sfackler/log4rs/13)
=> Optimize locking

src/append/file/mod.rs
Setting `append = false` on the file appender causes an error now:
```
log4rs: Error deserializing component: Invalid argument (os error 22)
log4rs: Error creating config: Reference to nonexistent appender: requests
```
The problem is that `std::fs::OpenOptions` fails on `.write(true).append(true).truncate(true)`. In case of `append=false` it must be changed to `.write(true).append(false).truncate(true)`.
The commit adds a test to reproduce the problem and fixes it.
=> Fix the problem with append=false in FileAppender

CHANGELOG.md, Cargo.toml, src/encode/json.rs, src/encode/pattern/mod.rs, src/lib.rs
Thread names are supported already, but this is definitely not enough.
Third-party libraries may not set thread names at all or use the
same name for multiple threads.
=> Support thread IDs in both JSON and pattern encoders.

src/lib.rs, src/priv_file.rs
Adds the `load_config_file` function that reads a configuration file,
but does not initialize it as `init_file` does.
We are using this modification to load logging configurations from .yaml files, but change the `Config` programmatically.
Signed-off-by: Logan Seeley <seeley@bitwise.io>
=> Allow loading config without initializing

src/encode/pattern/mod.rs
Allow specifying the process ID in `PatternEncoder` for including the current process ID in log formats.
=> Add Process ID to PatternEncoder

src/config.rs
Adds `set_level` methods to `Root` and `Config` objects. This provides
the ability to modify the logging level of `Root` even after `Root` and
`Config` have been built.
We are using this modification to change the logging level of a `Config` that is loaded from a .yaml file based on a verbosity flag that is passed in on the command line.
Signed-off-by: Logan Seeley <seeley@bitwise.io>
=> Add methods for modifying logging level of Root

CHANGELOG.md, Cargo.toml, README.md, src/append/console.rs, src/append/file.rs, src/append/mod.rs, src/append/rolling_file/mod.rs, src/append/rolling_file/policy/compound/mod.rs, src/append/rolling_file/policy/compound/roll/delete.rs, src/append/rolling_file/policy/compound/roll/fixed_window.rs, src/append/rolling_file/policy/compound/roll/mod.rs, src/append/rolling_file/policy/compound/trigger/mod.rs, src/append/rolling_file/policy/compound/trigger/size.rs, src/append/rolling_file/policy/mod.rs, src/config.rs, src/encode/json.rs, src/encode/mod.rs, src/encode/pattern/mod.rs, src/encode/writer/ansi.rs, src/encode/writer/console.rs, src/encode/writer/simple.rs, src/file.rs, src/filter/mod.rs, src/filter/threshold.rs, src/lib.rs, src/priv_file.rs
=> Update to edition 2018, deps and docs

Cargo.toml, src/append/rolling_file/policy/compound/roll/fixed_window.rs
Compression of large files during log rotation may take several seconds. At this time, all threads writing logs are blocked, which can lead to undesirable delays.
The problem is resolved when the rotation is executed in a separate thread. Library users can enable new behavior using feature `async_rotation`.
=> FixedWindowRoller: rotate log files in a separate thread

src/lib.rs
=> Add an init function which takes a RawConfig

src/file.rs
...if `json_encoder` or `pattern_encoder` specified but not both.
=> Fix 'use of undeclared type or module encode' error

src/encode/pattern/mod.rs
The current highlight colors are really hard to distinguish especially WARN and ERROR which are both red. This PR simply changes the colors to be the same as `env_logger`
* `ERROR` is still intense red
* `WARN` is now Yellow
* `INFO` is now Green
* `TRACE` is now intense black
* `DEBUG` is still white
=> Update highlight colors to be more distinguishable

src/config/mod.rs
`init_raw_config` introduced in 1.0.1-alpha-1 calls `log::set_max_level` with the hardcoded value of `Info`.
This PR makes it take the max level from the deserialized config, just like `init_config` does.
=> fix: init_raw_config forcing max_log_level to Info

src/encode/pattern/mod.rs
Fixes #184, makes text readable no matter the color scheme.
=> pattern encoder: Set trace to default color, reset formatting after

src/lib.rs
Just a small fix of a link found in the library documentation.
=> Fix link in documentation

Cargo.toml, src/append/mod.rs
The crates regex, regex_syntax, aho_coresick are all several
times bigger than log4rs itself and reg exps are only used in
one place to replace $ENV vars in paths.
Rewrite expand_env_vars() with a hand-coded scanner and
remote regex as dependency.
Closes #228
=> Rewrite expand_env_vars(), drop regex dependency

Cargo.toml, src/encode/mod.rs, src/encode/pattern/mod.rs
Add {i} and {tid} to allow logging in particular the Linux
thread ID as returned by gettid(). This is very useful for
system-wide debugging und monitoring with consistent
thread/task IDs.
Fixes: #231
=> Add support for gettid() to PatternEncoder

src/append/rolling_file/policy/compound/roll/fixed_window.rs
I am looking into resolving https://github.com/dtolnay/anyhow/issues/55 and this looks like one of only 2 places on crates.io where "{}" is used intentionally in an error message &mdash; meanwhile there were a couple dozen where it's a bug where they forgot to pass a second argument that was supposed to be interpolated in the message.
If you are open to tweaking this code, I'll land a fix for https://github.com/dtolnay/anyhow/issues/55 to help others catch missed format arguments.
=> Hide {} in error message from formatting machinery

src/lib.rs
I noticed the link to more examples in src/lib.rs is broken: the Markdown syntax is wrong for a link. This fixes it.
=> Fix link to more examples in src/lib.rs

Cargo.toml, src/config/raw.rs
Moves the typemap to point at the orphanage-rs implementation so we can address CVEs
Signed-off-by: Anton Whalley <anton@venshare.com>
=> fix:Update typemap to use orphanage-rs impl

.github/workflows/main.yml, Cargo.toml, README.md
Upgrade minimum rust version to 1.60 to allow usage of the latest log crate.
=> chore: update Rust version for latest log crate compatibility

.github/workflows/main.yml, Cargo.toml
Glad to see the PR moving again.
This PR will bump a series of dependencies.
Bump `arc-swap` from 1.2 to 1.6.
Bump `humantime` from 2.0 to 2.1.
Bump `serde_yaml` from 0.8.4 to 0.9.
Bump `toml` from 0.5 to 0.8.
Bump `parking_lot` from 2.0 to 2.1.
Bump `derivative` from 2.1.1 to 2.2.
Bump `tempfile` from 3.1.0 to 3.8.
=> chore(deps): Bump deps

.github/workflows/main.yml, Cargo.toml, README.md
Address #299 and adds a CI check to ensure compliance going forward.
=> ci: add auditing and fix cve

.rustfmt.toml, benches/rotation.rs, src/append/rolling_file/policy/compound/roll/fixed_window.rs
1. `merge_imports` is deprecated now, update it to `imports_granularity`.
2. Format code
=> chore: update deprecated merge_imports && fmt

src/encode/json.rs
I've changed the order of the fields for JSON output for better observability when logs are dumped in a file and require eye inspection.
I believe the following order
time - level - message - (rest of the log fields)... 
for the logs output would be better to catch the desired logs...
=> Changed the order of the field in json log output

.editorconfig, README.md, src/config/raw.rs
Fails parsing the current config. Seems to have been changed accidentally as it doesn't make sense that root and logger are defined within appenders.
=> Fix quickstart log4rs.yaml sample

.gitignore, src/config/mod.rs, src/config/raw.rs
=> fix: add check that the readme sample cfg is accepted by log4rs

Cargo.toml, src/encode/writer/console.rs, tests/color_control.rs
Test MR to add windows support to #302
=> apply no_color w/ windows cfg

.github/workflows/main.yml, Cargo.toml, README.md, src/append/rolling_file/policy/compound/mod.rs, src/config/raw.rs, src/config/runtime.rs
=> 352 readme cleanup

Cargo.toml, docs/Configuration.md, src/append/rolling_file/policy/compound/trigger/mod.rs, src/append/rolling_file/policy/compound/trigger/onstartup.rs, src/config/raw.rs, src/lib.rs
Add trigger onstartup, ref: [log4j](https://logging.apache.org/log4j/2.x/manual/appenders.html#onstartup-triggering-policy)
=> Add trigger `onstartup`

src/lib.rs
Remove lint "where_clauses_object_safety".
ref: https://github.com/rust-lang/rust/issues/51443
=> Fix clippy

src/config/mod.rs, src/lib.rs
Based on the discussion in issue https://github.com/estk/log4rs/issues/390 this is a proof-of-concept experiment that enables using log4rs in a multilog environment.
Probably naming, documentation and others can still be improved a lot, what do you think?
=> Made Handle accessible on logger enabling multilog environments

Cargo.toml, README.md, benches/rotation.rs, docs/Configuration.md, src/append/rolling_file/policy/compound/roll/fixed_window.rs
I would like to be able to compress log files with zstandard instead of gzip.
=> Add possibility to compress log files with Zstandard

Cargo.toml, src/encode/pattern/mod.rs, src/encode/pattern/parser.rs
=> fix unicode issues and implement left truncation

Cargo.toml, src/encode/writer/console.rs
Seeing that in the most recent RC release the MSRV has been bumped to 1.75, we can now use [OnceLock](https://doc.rust-lang.org/beta/std/sync/struct.OnceLock.html) which is available in 1.70 thus getting rid of the `OnceCell` dependency.
Tests fail locally, but they do the same on `main` currently.
Might be related to #365
=> feat: remove oncecell dependency

src/encode/writer/console.rs
I think a copy paste issue caused this with commit 4f09b8fd5e47dbccfe64ef91a464194b0e8ed053. It's been there a while
=> Bugfix: On windows stderr was erroneously written to stdout

Cargo.toml, src/encode/json.rs
When using the `JsonEncoder`, values captured for `serde` serialization (e.g., `key:serde = &value`) are incorrectly logged as their `Debug` or `Display` string representation, rather than as a nested JSON object.
**Example:**
A log statement like this:
```rust
log::info!(
response:serde = &MyStruct { id: 1 };
"Request completed"
);
```
Produces this output:
```json
{
"attributes": {
"response": "MyStruct { id: 1 }"
},
...
}
```
Instead of the expected output:
```json
{
"attributes": {
"response": { "id": 1 }
},
...
}
```
=> Fix `JsonEncoder` not using serde for `Serialize` types

.cargo/config.toml, .github/workflows/main.yml, Cargo.toml, README.md, src/encode/json.rs, src/encode/pattern/mod.rs, src/encode/writer/console.rs
This builds upon the work of @upendra1997. The following work was stacked upon his original PR #407:
- Reorganized target-specific dependencies.
- Rebased onto main.
- Removed `libc::isatty` tests in the `Writer` impl in `console.rs`.
- Added `.cargo/config.toml` to tell Cargo to use the `--cfg getrandom_backend="wasm_js"` Rust flag, required for the `rand`/`getrandom` dependencies.
- Added a blurb in the README.md about the need for the above Rust flags.
~This is a DRAFT until the following questions are resolved:~ See discussion below.
- ~`getrandom`, a transitive dependency of the `rand` crate, requires special treatment for a Wasm target. However, `rand` is only included if the `time_trigger` feature is enabled, which it is by default. Does this feature make sense for Wasm targets? If …
=> Adding wasm as target
