estk/log4rs

- Cargo.toml
- src/encode/pattern/mod.rs
> update chrono version to 0.4

- appveyor.yml
- src/append/rolling_file/policy/compound/roll/fixed_window.rs
- src/encode/json.rs
see 
https://ci.appveyor.com/project/uwearzt/log4rs/build/1.0.3
https://github.com/sfackler/log4rs/issues/49
If you have additional wishes, let me know :)
> Appveyor support + Windows Testfixes

- Cargo.toml
- src/append/rolling_file/policy/compound/roll/fixed_window.rs
- src/encode/writer/console.rs
- src/file.rs
- src/lib.rs
- src/priv_file.rs
Hi there,
This is a little extension allows to use configurations in xml (optional feature)
> xml format for configuration file

- .circleci/config.yml
- Cargo.toml
- src/lib.rs
https://github.com/sfackler/log4rs/issues/82
> upgrade crossbeam to 0.4.1 to address rust sec vuln

- src/lib.rs
> make logger public

- .circleci/config.yml
- src/append/console.rs
- src/append/file.rs
- src/append/mod.rs
- src/append/rolling_file/mod.rs
- src/append/rolling_file/policy/compound/mod.rs
- src/append/rolling_file/policy/compound/roll/delete.rs
- src/append/rolling_file/policy/compound/roll/fixed_window.rs
- src/append/rolling_file/policy/compound/roll/mod.rs
- src/append/rolling_file/policy/compound/trigger/mod.rs
- src/append/rolling_file/policy/compound/trigger/size.rs
- src/append/rolling_file/policy/mod.rs
- src/config.rs
- src/encode/json.rs
- src/encode/mod.rs
- src/encode/pattern/mod.rs
- src/encode/pattern/parser.rs
- src/encode/writer/ansi.rs
- src/encode/writer/console.rs
- src/file.rs
- src/filter/mod.rs
- src/filter/threshold.rs
- src/lib.rs
- src/priv_file.rs
> Clippy fixes, derive basic traits

- .editorconfig
Idk if the github action will work
> Github action for editorconfig

- Cargo.toml
@estk 👋 I was looking at issue #101 if there's anything else i can help out with please let me know
😄
> #101 Cleaning up manifest file

- cross-test.sh
- src/encode/writer/console.rs
> Fix console writer in windows, add test script.

- .github/workflows/main.yml
- README.md
- cross-test.sh
- src/append/rolling_file/mod.rs
- test.sh
Change to github workflows so we can build windows
> Add github workflows

- src/append/rolling_file/policy/compound/roll/fixed_window.rs
- src/lib.rs
I finally got around to this, let me know if any of the wording or organization should be tweaked! This is the PR for #112
> Improve doc discoverability

- Cargo.toml
- README.md
- benches/rotation.rs
> Add back gzip to default features update docs

- Cargo.toml
- src/append/console.rs
- src/append/file.rs
- src/append/mod.rs
- src/append/rolling_file/mod.rs
- src/append/rolling_file/policy/compound/mod.rs
- src/append/rolling_file/policy/compound/roll/delete.rs
- src/append/rolling_file/policy/compound/roll/fixed_window.rs
- src/append/rolling_file/policy/compound/roll/mod.rs
- src/append/rolling_file/policy/compound/trigger/mod.rs
- src/append/rolling_file/policy/compound/trigger/size.rs
- src/append/rolling_file/policy/mod.rs
- src/config.rs
- src/encode/json.rs
- src/encode/mod.rs
- src/encode/pattern/mod.rs
- src/file.rs
- src/filter/threshold.rs
- src/lib.rs
- src/priv_file.rs
fail all the things.
Edit: closes #131
> Expose errors as failure::Error

- Cargo.toml
- src/file.rs
- src/priv_file.rs
I can't make an actual 1.0 branch, but here's a PR for removing XML configs.
Edit: closes #129
> Issue #129: Drop XML Config support

- .github/workflows/main.yml
- Cargo.toml
- src/append/console.rs
- src/append/file.rs
- src/append/mod.rs
- src/append/rolling_file/mod.rs
- src/append/rolling_file/policy/compound/mod.rs
- src/append/rolling_file/policy/compound/roll/delete.rs
- src/append/rolling_file/policy/compound/roll/fixed_window.rs
- src/append/rolling_file/policy/compound/roll/mod.rs
- src/append/rolling_file/policy/compound/trigger/mod.rs
- src/append/rolling_file/policy/compound/trigger/size.rs
- src/append/rolling_file/policy/mod.rs
- src/config_parsing.rs
- src/encode/json.rs
- src/encode/mod.rs
- src/encode/pattern/mod.rs
- src/filter/mod.rs
- src/filter/threshold.rs
- src/lib.rs
- src/priv_file.rs
> Rename file feature

- src/append/mod.rs
- src/config/file.rs
- src/config/mod.rs
- src/config/raw.rs
- src/config/runtime.rs
- src/encode/pattern/mod.rs
I want to better follow api guidelines here, we should be exporting non-erased errors since we're a lib. There are some limitations since we're allowing for plugin crates.
> Errors 1.0

- CHANGELOG.md
- src/config/mod.rs
- src/lib.rs
Allow registration of a custom error handler for the handle.
> Custom err handler

- Cargo.toml
> update arc-swap to latest

- Cargo.toml
- examples/compile_time_config.rs
- examples/sample_config.yml
An example to address the frequently asked question. Addresses: #223
> Add example of using compile time config

- src/append/file.rs
- src/append/mod.rs
- src/append/rolling_file/mod.rs
- src/append/rolling_file/policy/compound/roll/fixed_window.rs
This PR implements expanding env vars in file patterns in `FixedWindowRoller` as requested here https://github.com/estk/log4rs/issues/280 .
> Fixed window roller expand env var

- README.md
@estk Fixing the version from 1.56 -> 1.67 the current MSRV of the project.
> doc: fix msrv badge

- .gitignore
- Cargo.toml
- docs/Configuration.md
- examples/compile_time_config.rs
- examples/sample_config.yml
- src/append/rolling_file/mod.rs
- src/append/rolling_file/policy/compound/mod.rs
- src/append/rolling_file/policy/compound/trigger/mod.rs
- src/append/rolling_file/policy/compound/trigger/size.rs
- src/append/rolling_file/policy/compound/trigger/time.rs
- src/append/rolling_file/policy/mod.rs
- src/config/raw.rs
- src/lib.rs
I add the trigger kind "time" in rolling_file. It can be set with limit like 5second, 10minute, 1day, 3weeks...It may be able to solve the Issue #235. I referred to #139  and thank for @SSebo
> add trigger kind "time" in rolling_file

- .github/workflows/main.yml
- CHANGELOG.md
- Cargo.toml
- README.md
Title says it all. Thoughts on waiting for #302 / #335?
> docs: Update CHANGELOG for new release

- docs/Configuration.md
> Two minor typo fixes in `Configuration.md`.
